version: 0.2

env:
    parameter-store:
      RUNNERUSER: AA_runner_user
      #RUNNERDEVICE: AA_runner_device

phases:
  pre_build:
    commands:
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - cd $CODEBUILD_SRC_DIR
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform apply -var-file="dev-app.tfvars" --auto-approve

  #post_build:
  #  commands:
  #   #- RUNNERDEVICE = terraform output private_dns
  #   - aws lambda update-function-configuration --function-name RegisterDeviceA360 --environment "Variables={runnerUser=${RUNNERUSER},runnerDevice=${RUNNERDEVICE}}"
